# Generated by Django 3.1.5 on 2021-01-20 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0003_auto_20210117_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_User_Occurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('testId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.test')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.user')),
            ],
        ),
    ]
