# Generated by Django 3.1.5 on 2021-01-21 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0004_test_user_occurrence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_User_Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('questionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.question')),
            ],
        ),
    ]
