# Generated by Django 3.1.5 on 2021-01-21 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0006_auto_20210121_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_user_questions',
            name='occurrenceId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testApp.test_user_occurrence'),
            preserve_default=False,
        ),
    ]
